debug: true
  
server:
  port: 8081
  
spring:
  cloud:
    config:
      server:
        git:
          default-label: Microservicios-Config-Service
          uri: https://github.com/canaritel/Microservicios-Ventas.git
          search-paths: Microservicios-Config-Data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
        bootstrap: true
  application:
    name: Microservicios-Config-Service

  security:
    user:
      name: root
      password: s3cr3t
       