server:
  port: 8090
  include-message: always
  include-binding-errors: always
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: suecia
    url: jdbc:mariadb://localhost:3306/microser_ventas
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
  mustache:
    check-template-location: false
  sql:
    init:
      platform: mariadb
      mode: always
