logging:
  level:
    org:
      hibernate: warn
      springframework:
        web: info
    root: info
server:
  port: 8093
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: suecia
    url: jdbc:mariadb://localhost:3306/microser_shooping
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
  mustache:
    check-template-location: false
  sql:
    init:
      platform: mariadb
      mode: always
